import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'background': '#121412',
        'surface': '#121412',
        'surface-dim': '#121412',
        'surface-container-lowest': '#0d0f0d',
        'surface-container-low': '#1b1c1a',
        'surface-container': '#1f201e',
        'surface-container-high': '#292a28',
        'surface-container-highest': '#343533',
        'surface-bright': '#383937',
        'surface-variant': '#343533',
        'on-surface': '#e3e2df',
        'on-surface-variant': '#cfc4c5',
        'on-background': '#e3e2df',
        'primary': '#cac5c5',
        'on-primary': '#323030',
        'primary-container': '#111010',
        'on-primary-container': '#7f7c7b',
        'primary-fixed': '#e6e1e1',
        'primary-fixed-dim': '#cac5c5',
        'on-primary-fixed': '#1c1b1b',
        'on-primary-fixed-variant': '#484646',
        'inverse-surface': '#e3e2df',
        'inverse-on-surface': '#30312e',
        'inverse-primary': '#605e5e',
        'secondary': '#cac6c2',
        'on-secondary': '#32302e',
        'secondary-container': '#4b4946',
        'on-secondary-container': '#bbb8b4',
        'secondary-fixed': '#e6e2de',
        'secondary-fixed-dim': '#cac6c2',
        'on-secondary-fixed': '#1c1b19',
        'on-secondary-fixed-variant': '#484644',
        'tertiary': '#e3c285',           // Gold accent — use sparingly
        'on-tertiary': '#402d00',
        'tertiary-container': '#180f00',
        'on-tertiary-container': '#947942',
        'tertiary-fixed': '#ffdea3',
        'tertiary-fixed-dim': '#e3c285',
        'on-tertiary-fixed': '#261900',
        'on-tertiary-fixed-variant': '#594312',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'outline': '#988e8f',
        'outline-variant': '#4d4546',
        'border-subtle': '#2A2826',
        'text-secondary': '#9A9590',
        'nav-overlay': '#111010d1',
        'accent-hover': '#A08550',
        'surface-tint': '#cac5c5',
      },
      borderRadius: {
        DEFAULT: '0',
        lg: '0',
        xl: '0',
        full: '0',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'marquee-reverse': {
          '0%': { transform: 'translateX(-50%)' },
          '100%': { transform: 'translateX(0)' },
        }
      },
      animation: {
        marquee: 'marquee 40s linear infinite',
        'marquee-reverse': 'marquee-reverse 40s linear infinite',
      },
      spacing: {
        'margin-desktop': 'var(--margin-page)',
        'margin-mobile': 'var(--margin-page)',
        'reading-max': '720px',
        'container-max': '1440px',
        'section-desktop': 'var(--section-padding)',
        'section-tablet': 'var(--section-padding)',
        'intra-section': 'clamp(2rem, 4vw, 3rem)',
        'gutter-desktop': 'var(--gutter)',
        'section-mobile': 'var(--section-padding)',
      },
      fontFamily: {
        'display':        ['var(--font-cormorant)', 'Georgia', 'serif'],
        'display-mobile': ['var(--font-cormorant)', 'Georgia', 'serif'],
        'headline-lg':    ['var(--font-cormorant)', 'Georgia', 'serif'],
        'headline-md':    ['var(--font-cormorant)', 'Georgia', 'serif'],
        'pullquote':      ['var(--font-cormorant)', 'Georgia', 'serif'],
        'metric-hero':    ['var(--font-cormorant)', 'Georgia', 'serif'],
        'body':           ['var(--font-dm-sans)', 'system-ui', 'sans-serif'],
        'nav':            ['var(--font-dm-sans)', 'system-ui', 'sans-serif'],
        'label-caps':     ['var(--font-dm-sans)', 'system-ui', 'sans-serif'],
        'caption':        ['var(--font-dm-sans)', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display':        ['clamp(2.75rem, 5.8vw, 6.875rem)', { lineHeight: '1.05', letterSpacing: '0em',   fontWeight: '300' }],
        'display-mobile': ['clamp(2.25rem, 4.5vw, 3rem)',    { lineHeight: '1.1',  letterSpacing: '0em',   fontWeight: '300' }],
        'headline-lg':    ['clamp(2.25rem, 4.2vw, 4rem)',     { lineHeight: '1.1',  letterSpacing: '0em',   fontWeight: '400' }],
        'headline-md':    ['clamp(1.75rem, 3.2vw, 3rem)',     { lineHeight: '1.15', letterSpacing: '0em',   fontWeight: '400' }],
        'pullquote':      ['clamp(1.35rem, 2.4vw, 2.25rem)',  { lineHeight: '1.35',                          fontWeight: '300' }],
        'metric-hero':    ['clamp(3.5rem, 7vw, 6.5rem)',      { lineHeight: '1.0',                           fontWeight: '300' }],
        'body':           ['18px',  { lineHeight: '1.7',  letterSpacing: '0em',   fontWeight: '400' }],
        'nav':            ['13px',  { lineHeight: '1.0',  letterSpacing: '0.12em',fontWeight: '400' }],
        'label-caps':     ['12px',  { lineHeight: '1.4',  letterSpacing: '0.15em',fontWeight: '500' }],
        'caption':        ['13px',  { lineHeight: '1.5',                           fontWeight: '400' }],
      },
    },
  },
  plugins: [],
} satisfies Config
